# Generated by Django 5.1.7 on 2025-03-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_provider_name', models.CharField(max_length=100)),
                ('product_receiver_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_weight', models.IntegerField(max_length=3)),
                ('product_location', models.CharField(max_length=15)),
            ],
        ),
    ]
