# Generated by Django 5.1.7 on 2025-03-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='product_weight',
            field=models.IntegerField(),
        ),
    ]
