# Generated by Django 5.1.7 on 2025-03-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_alter_courier_product_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='product_weight',
            new_name='p_weight_in_kg',
        ),
    ]
